Traceback (most recent call last):
  File "/Users/eelco/opt/anaconda3/envs/jbooktest/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/eelco/opt/anaconda3/envs/jbooktest/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/eelco/opt/anaconda3/envs/jbooktest/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/eelco/opt/anaconda3/envs/jbooktest/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/Users/eelco/opt/anaconda3/envs/jbooktest/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/Users/eelco/opt/anaconda3/envs/jbooktest/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/Users/eelco/opt/anaconda3/envs/jbooktest/lib/python3.10/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/eelco/opt/anaconda3/envs/jbooktest/lib/python3.10/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
fig = !echo 'digraph { a -> b }' | dot -Tsvg 
display(SVG(fig ))
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mTypeError[0m                                 Traceback (most recent call last)
Input [0;32mIn [4][0m, in [0;36m<cell line: 2>[0;34m()[0m
[1;32m      1[0m fig [38;5;241m=[39m get_ipython()[38;5;241m.[39mgetoutput([38;5;124m"[39m[38;5;124mecho [39m[38;5;124m'[39m[38;5;124mdigraph [39m[38;5;124m{[39m[38;5;124m a -> b }[39m[38;5;124m'[39m[38;5;124m | dot -Tsvg[39m[38;5;124m"[39m)
[0;32m----> 2[0m display([43mSVG[49m[43m([49m[43mfig[49m[43m [49m[43m)[49m)

File [0;32m~/opt/anaconda3/envs/jbooktest/lib/python3.10/site-packages/IPython/core/display.py:320[0m, in [0;36mDisplayObject.__init__[0;34m(self, data, url, filename, metadata)[0m
[1;32m    316[0m [38;5;28mself[39m[38;5;241m.[39mfilename [38;5;241m=[39m filename
[1;32m    317[0m [38;5;66;03m# because of @data.setter methods in[39;00m
[1;32m    318[0m [38;5;66;03m# subclasses ensure url and filename are set[39;00m
[1;32m    319[0m [38;5;66;03m# before assigning to self.data[39;00m
[0;32m--> 320[0m [38;5;28mself[39m[38;5;241m.[39mdata [38;5;241m=[39m data
[1;32m    322[0m [38;5;28;01mif[39;00m metadata [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m:
[1;32m    323[0m     [38;5;28mself[39m[38;5;241m.[39mmetadata [38;5;241m=[39m metadata

File [0;32m~/opt/anaconda3/envs/jbooktest/lib/python3.10/site-packages/IPython/core/display.py:479[0m, in [0;36mSVG.data[0;34m(self, svg)[0m
[1;32m    477[0m [38;5;66;03m# parse into dom object[39;00m
[1;32m    478[0m [38;5;28;01mfrom[39;00m [38;5;21;01mxml[39;00m[38;5;21;01m.[39;00m[38;5;21;01mdom[39;00m [38;5;28;01mimport[39;00m minidom
[0;32m--> 479[0m x [38;5;241m=[39m [43mminidom[49m[38;5;241;43m.[39;49m[43mparseString[49m[43m([49m[43msvg[49m[43m)[49m
[1;32m    480[0m [38;5;66;03m# get svg tag (should be 1)[39;00m
[1;32m    481[0m found_svg [38;5;241m=[39m x[38;5;241m.[39mgetElementsByTagName([38;5;124m'[39m[38;5;124msvg[39m[38;5;124m'[39m)

File [0;32m~/opt/anaconda3/envs/jbooktest/lib/python3.10/xml/dom/minidom.py:1998[0m, in [0;36mparseString[0;34m(string, parser)[0m
[1;32m   1996[0m [38;5;28;01mif[39;00m parser [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m:
[1;32m   1997[0m     [38;5;28;01mfrom[39;00m [38;5;21;01mxml[39;00m[38;5;21;01m.[39;00m[38;5;21;01mdom[39;00m [38;5;28;01mimport[39;00m expatbuilder
[0;32m-> 1998[0m     [38;5;28;01mreturn[39;00m [43mexpatbuilder[49m[38;5;241;43m.[39;49m[43mparseString[49m[43m([49m[43mstring[49m[43m)[49m
[1;32m   1999[0m [38;5;28;01melse[39;00m:
[1;32m   2000[0m     [38;5;28;01mfrom[39;00m [38;5;21;01mxml[39;00m[38;5;21;01m.[39;00m[38;5;21;01mdom[39;00m [38;5;28;01mimport[39;00m pulldom

File [0;32m~/opt/anaconda3/envs/jbooktest/lib/python3.10/xml/dom/expatbuilder.py:925[0m, in [0;36mparseString[0;34m(string, namespaces)[0m
[1;32m    923[0m [38;5;28;01melse[39;00m:
[1;32m    924[0m     builder [38;5;241m=[39m ExpatBuilder()
[0;32m--> 925[0m [38;5;28;01mreturn[39;00m [43mbuilder[49m[38;5;241;43m.[39;49m[43mparseString[49m[43m([49m[43mstring[49m[43m)[49m

File [0;32m~/opt/anaconda3/envs/jbooktest/lib/python3.10/xml/dom/expatbuilder.py:223[0m, in [0;36mExpatBuilder.parseString[0;34m(self, string)[0m
[1;32m    221[0m parser [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39mgetParser()
[1;32m    222[0m [38;5;28;01mtry[39;00m:
[0;32m--> 223[0m     [43mparser[49m[38;5;241;43m.[39;49m[43mParse[49m[43m([49m[43mstring[49m[43m,[49m[43m [49m[38;5;28;43;01mTrue[39;49;00m[43m)[49m
[1;32m    224[0m     [38;5;28mself[39m[38;5;241m.[39m_setup_subset(string)
[1;32m    225[0m [38;5;28;01mexcept[39;00m ParseEscape:

[0;31mTypeError[0m: a bytes-like object is required, not 'SList'
TypeError: a bytes-like object is required, not 'SList'

